version: "3.8"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'supersecurepassword'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['db_port'] = 5432
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    depends_on:
      - redis
      - postgres
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: gitlabhq_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  postgres_data:
  redis_data: